### ISSUE TITLE
Nested Regions?

### ISSUE THREAD

**Issue by Allenite** [berabue/vscode-region-viewer#1]
This is incredibly useful for VSC.  Can you also consider adding nested regions?

#Region abc
`some code`

#Region def
`some more code`

#endregion def
#endregion abc

would ideally return this if nested:
#abc
   #def

**Comment by swift502** [comment]
I found this example: https://stackoverflow.com/questions/56534723/simple-example-to-implement-vs-code-treedataprovider-with-json-data

Looks like what we need.

**Comment by swift502** [comment]
I think I got it.
![image](https://user-images.githubusercontent.com/24359130/88719669-f1dbdd00-d123-11ea-874a-d7f1d6934b3e.png)

It's here. 
It's a first pass. I'll polish it up and make a PR once / if @berabue accepts my current PRs.

**Comment by berabue** [comment]
@Allenite 

The function you want has just been released.

I would like to express my infinite gratitude to @swift502 for making this feature.

**Comment by Allenite** [comment]
Thank you so much @swift502  and @berabue
