### ISSUE TITLE
Error adding a language support

### ISSUE THREAD

**Issue by ylazy** [berabue/vscode-region-viewer#28]
I got this error:

`Error running command region-viewer.activeDocumentLanguageId: command 'region-viewer.activeDocumentLanguageId' not found. This is likely caused by the extension that contributes region-viewer.activeDocumentLanguageId.`

I defined my language in settings.json:

```
"region-viewer.markers-overrides":
{
    "actionscript":
    {
        "start": "^\\s*//\\s*(?:(?:#?region\\b(?<name>.*))",
        "end": "^\\s*//\\s*(?:(?:#?endregion\\b)"
    },
},
```

**Comment by KOTRET** [comment]
I can see 3 opening brackets, but only 2 closing for the start tag.

**Comment by ylazy** [comment]
> I can see 3 opening brackets, but only 2 closing for the start tag.

It worked! Thank you so much!
