### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by swift502** [berabue/vscode-region-viewer#6]
Hi,

Just wondering what's the purpose of having vscode-region-viewer > santacodes-region-viewer folder structure and two readme.md files. From what I've seen, VSCode extensions don't usually look like this.

Is there a reason behind that? Could we simplify it and only leave the vscode-region-viewer folder?

Thanks.

**Comment by berabue** [comment]
I accepted your opinion and changed the folder structure.

I'm new to extensions, so the folder structure and package name are messed up. 😢

**Comment by swift502** [comment]
Cool. 🙂 
I think it's better like this. It'll be less confusing for anyone wanting to contribute.
